site_name: CytoBulk's Docs

theme:
  name: "material"
  logo: assets/logo_temp.png
  favicon: assets/favicon_temp.png
  features:
    - search.suggest
    - search.highlight
    - search.share\
    - navigation.footer
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  homepage: https://github.com/kristaxying/CytoBulk
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kristaxying/CytoBulk

copyright: Copyright &copy; 2023 WANG Xueying WANG Yian

repo_url: https://kristaxying.github.io/CytoBulk/
repo_name: CytoBulk

plugins:
  - mknotebooks:
      encoding: 'utf-8'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - search
extra:
  encoding: 'utf-8'



markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences

nav:
- Home: index.md
- Install: Install.md
- API References:

  - deconv: ./tools/_deconv.md
  - mapping: ./tools/_mapping.md
  - segmentation: ./tools/_segmentation.md
  - plot: ./plots/_plot.md
- Examples: 
  - ST data deconvolution and spot annotation: ./tutorials/he_deconv_anno.ipynb
  - Bulk deconvolution and mapping with scRNA-seq: ./tutorials/mapping_sc_bulk.ipynb
  - ST deconvolution and mapping with scRNA-seq: ./tutorials/mapping_sc_st.ipynb
  - H&E cell prediction and integration with scRNA-seq: ./tutorials/mapping_he_sc.ipynb
- References: References.md
