site_name: CytoBulk's Docs

theme:
  name: "material"
  logo: assets/logo_temp.png
  favicon: assets/favicon_temp.png
  features:
    - search.suggest
    - search.highlight
    - search.share\
    - navigation.footer
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  homepage: https://github.com/kristaxying/CytoBulk
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kristaxying/CytoBulk

copyright: Copyright &copy; 2023 WANG Xueying WANG Yian

repo_url: https://github.com/kristaxying/CytoBulk
repo_name: CytoBulk

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
- search

nav:
- Home: index.md
- API References:
  - preprocessing:
    - _filtering: ./preprocessing/_filtering.md
    - _preprocessing: ./preprocessing/_preprocessing.md
  - tools:
    - deconv: ./tools/_deconv.md
    - mapping: ./tools/_mapping.md
    - segmentation: ./tools/_segmentation.md
  - plots:
    - plot: ./plots/_plot.md
- Examples: Examples.md
- References: References.md
